version: '2'

volumes:
  cassandra-storage-go-api-learn:

services:
  go-api-learn-cassandra-node1:
    image: cassandra:3.11
    container_name: "go-api-learn-cassandra-node1"
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    volumes:
      - cassandra-storage-go-api-learn:/var/lib/cassandra
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
#      - "7199:7199" # JMX
#      - "7000:7000" # cluster communication
#      - "7001:7001" # cluster communication (SSL)
      - "9042:9042" # native protocol clients
      - "9160:9160" # thrift clients

  go-api-learn-cassandra-node2:
    image: cassandra:3.11
    container_name: "go-api-learn-cassandra-node2"
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
    volumes:
      - cassandra-storage-go-api-learn:/var/lib/cassandra
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
#      - "7199:7199" # JMX
#      - "7000:7000" # cluster communication
#      - "7001:7001" # cluster communication (SSL)
      - "9043:9042" # native protocol clients
      - "9161:9160" # thrift clients